Repository fusionjs/fusion-cli, pull requests merged in 2018-08, with the labels that each got.

#473 Make react/enzyme dependency soft
  build/jest/base-jest-config.js
  build/server-error.js
  package.json
  test/fixtures/test-jest-app/package.json
  yarn.lock
Labels: bugfix

#477 Prevent tree-shaking of polyfills
  build/compiler.js
  entries/client-entry.js
Labels: bugfix

#478 Release v1.9.0-beta.1
  package.json
Labels: release

#479 Upgrade dependencies and fix new flow errors
  build/spawn.js
  build/webpack-state.js
  package.json
  test/run-command.js
  yarn.lock
Labels: greenkeeping

#482 Revert require.cache busting
  build/jest/base-jest-config.js
  build/jest/jest-config.js
  build/jest/jest-transformer.js
Labels: bugfix

#483 Release 1.9.1-0
  package.json
Labels: prerelease, release

#487 Release v1.9.1-1
  package.json
Labels: release

#489 Upgrade dependencies
  build/convert-coverage.js
  package.json
  yarn.lock
Labels: greenkeeping

#490 Add name for each environment to jest config
  build/jest/jsdom/jest.config.js
  build/jest/node/jest.config.js
Labels: bugfix
