Repository fusionjs/fusion-cli, pull requests merged in 2018-07, with the labels that each got.

#413 Release v1.8.0
  package.json
Labels: release

#417 Release v1.8.1
  package.json
Labels: release

#419 Release v1.8.2
  package.json
Labels: release

#423 Release v1.8.3
  package.json
Labels: release

#436 Release v1.8.4-beta.0
  package.json
Labels: release

#437 Add documentation on why we dont allow customizations of webpack config
  README.md
Labels: docs

#443 Release v1.8.4-beta.1
  package.json
Labels: release

#448 Fix issue with dev process crashing
  build/dev-runtime.js
  commands/dev.js
  test/index.js
Labels: bugfix

#450 Release v1.8.4
  package.json
Labels: release

#453 Release v1.8.5-0
  package.json
Labels: release

#456 Release v1.8.5
  package.json
Labels: release
