Repository fusionjs/fusion-cli, pull requests merged in 2018-09, with the labels that each got.

#501 Add no-cache flag when --debug is set
  build/test-runtime.js
Labels: bugfix

#495 Add cacheablePaths to context
  build/compiler.js
  build/loaders/cacheable-paths-loader.js
  build/loaders/index.js
  build/loaders/loader-context.js
  build/plugins/cacheable-paths-state-hydrator-plugin.js
  build/types.js
  get-compilation-metadata.js
  plugins/context-plugin.js
  test/cli/dev.js
  test/fixtures/assets/src/main.js
Labels: feature

#502 Support a whitelist of Jest CLI arguments
  build/jest/cli-options.js
  build/test-runtime.js
  commands/index.js
  commands/test.js
Labels: feature

#503 Release v1.10.0
  package.json
Labels: release

#505 Add @babel/plugin-transform-flow-strip-types in favor of @babel/preset-flow
  build/babel-plugins/babel-plugin-utils/test/index.js
  build/get-babel-config.js
  package.json
  test/cli/test.js
  test/fixtures/test-jest-app/src/__tests__/class-props.js
  test/fixtures/test-jest-app/src/class-props.js
  yarn.lock
Labels: bugfix

#506 Release v1.10.1
  package.json
Labels: release

#507 Release v1.10.2
  package.json
Labels: release

#508 Release v1.10.3-0
  package.json
Labels: release

#509 Fix JSON file assetURL usage
  build/babel-plugins/babel-plugin-asseturl/index.js
  build/babel-plugins/babel-plugin-asseturl/test/fixtures/expected-import-destructuring
  build/babel-plugins/babel-plugin-asseturl/test/fixtures/expected-import-destructuring-as
  build/compiler.js
  build/loaders/file-loader.js
  build/loaders/json-loader.js
  package.json
  test/cli/dev.js
  test/fixtures/assets-client-fetch/src/home.js
  test/fixtures/assets-client-fetch/src/main.js
  test/fixtures/assets-client-fetch/static/test.json
  test/fixtures/json-static-assets/src/home.js
  test/fixtures/json-static-assets/src/main.js
  test/fixtures/json-static-assets/static/test.json
  yarn.lock
Labels: bugfix

#510 Fix assetUrl with binary assets
  build/loaders/file-loader.js
Labels: bugfix

#494 Remove vestigial code
  build/webpack-state.js
Labels: bugfix

#512 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping

#514 Revert "Add cacheablePaths to context"
  build/compiler.js
  build/loaders/cacheable-paths-loader.js
  build/loaders/index.js
  build/loaders/loader-context.js
  build/plugins/cacheable-paths-state-hydrator-plugin.js
  build/types.js
  get-compilation-metadata.js
  plugins/context-plugin.js
  test/cli/dev.js
  test/fixtures/assets/src/main.js
Labels: bugfix

#511 Release v1.10.4-0
  package.json
Labels: release

#516 Fix Flow-annotated class properties/methods
  build/get-babel-config.js
  package.json
  yarn.lock
Labels: bugfix

#517 Release v1.10.4-1
  package.json
Labels: release

#518 Fix missing translations in dev after rebuild
  build/plugins/i18n-discovery-plugin.js
  test/cli/dev.js
Labels: bugfix

#519 Release v1.10.4-2
  package.json
Labels: release

#524 Fix polyfilling with sideEffectFree option and add regression test
  entries/client-entry.js
  test/cli/build.js
Labels: bugfix

#525 Release v1.10.4
  package.json
Labels: release

#527 Add experimentalCompile flag
  build/compiler.js
  build/load-fusionrc.js
  test/compiler/api.js
  test/fixtures/transpile-all-files/.fusionrc.js
  test/fixtures/transpile-all-files/common/test.js
  test/fixtures/transpile-all-files/src/main.js
Labels: feature

#528 Use require.resolve rather than requiring modules directly
  build/get-babel-config.js
Labels: bugfix

#529 Release v1.11.0-0
  package.json
Labels: release

#531 Fix chunk hashing, refactor JS asset code
  build/compiler.js
  build/loaders/chunk-manifest-loader.js
  build/plugins/client-chunk-metadata-state-hydrator-plugin.js
  build/types.js
  entries/client-entry.js
  entries/client-public-path.js
  entries/server-entry.js
  entries/server-public-path.js
  package.json
  plugins/context-plugin.js
  plugins/critical-chunk-ids-plugin.js
  plugins/ssr-plugin.js
  test/cli/build.js
  yarn.lock
Labels: bugfix
