Repository fusionjs/fusion-cli, pull requests merged in 2018-11, with the labels that each got.

#605 Fix race condition in script loading
  plugins/ssr-plugin.js
  test/cli/build.js
Labels: bugfix

#607 Release v1.13.0-beta.10
  package.json
Labels: release

#611 Fix EADDRINUSE error in dev
  build/dev-runtime.js
Labels: bugfix

#612 Switch to parser-inserted scripts, fix script preloading for legacy bundles
  build/get-webpack-config.js
  plugins/ssr-plugin.js
  test/cli/build.js
Labels: bugfix

#613 Release v1.13.0-beta.11
  package.json
Labels: release

#614 Ensure credentials are sent for same-origin module chunks
  plugins/ssr-plugin.js
  test/cli/build.js
Labels: bugfix

#615 Release v1.13.0-beta.12
  package.json
Labels: release

#616 Remove nomodule attributes when only serving legacy scripts
  plugins/ssr-plugin.js
Labels: bugfix

#617 Release v1.13.0-beta.13
  package.json
Labels: release

#618 Fix runtime chunk in legacy bundles
  build/plugins/chunk-id-prefix-plugin.js
  test/cli/build.js
  test/fixtures/dynamic-import-app/src/main.js
Labels: bugfix

#619 Release v1.13.0-beta.14
  package.json
Labels: release

#623 Add support for ignoring files in coverage with collectCoverageFrom config
  build/jest/base-jest-config.js
  build/jest/cli-options.js
  build/test-runtime.js
  commands/index.js
  commands/test.js
  test/cli/test.js
  test/fixtures/test-jest-app/src/istanbul-ignore-coverage-cli.js
  test/fixtures/test-jest-app/src/istanbul-ignore-coverage.js
  test/fixtures/test-jest-app/src/main.js
Labels: feature

#625 Fix types
  build/compiler.js
  build/get-webpack-config.js
  build/shared-state-containers.js
  package.json
  plugins/assets-plugin.js
  plugins/context-plugin.js
  plugins/critical-chunk-ids-plugin.js
  plugins/server-error-plugin.js
  plugins/ssr-plugin.js
  plugins/types.js
  test/cli/build.js
  test/cli/dev.js
  yarn.lock
Labels: bugfix

#633 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
