Repository fusionjs/fusion-cli, pull requests merged in 2018-10, with the labels that each got.

#538 Release v1.11.0
  package.json
Labels: release

#539 Update compression-webpack-plugin@2.x and compression options
  lib/compression/brotli-webpack-plugin.js
  lib/compression/svgo-webpack-plugin.js
  lib/compression/zopfli-webpack-plugin.js
  package.json
  yarn.lock
Labels: dependencies, greenkeeping

#541 Remove vestigial webpack-dev-server config
  build/compiler.js
Labels: refactor

#545 Fix incorrect sourcemap filenames
  build/compiler.js
  package.json
  test/cli/build.js
  yarn.lock
Labels: bugfix

#543 Update snapshot command in test
  package.json
  test/cli/test.js
  yarn.lock
Labels: bugfix, greenkeeping

#548 Fix client-side RoutePrefixToken registration
  entries/client-entry.js
  test/cli/build.js
  test/fixtures/prefix/src/main.js
Labels: bugfix

#535 Add test for customizing SSR body template
  entries/server-entry.js
  test/cli/dev.js
  test/fixtures/custom-body-template/src/main.js
Labels: refactor

#549 Release v1.11.2
  package.json
Labels: release

#550 Fix client-side token registration error
  entries/client-entry.js
  test/cli/build.js
Labels: bugfix

#551 Release v1.11.3
  package.json
Labels: release

#552 Fix assetUrl in dev in certain instances
  build/compiler.js
  build/loaders/file-loader.js
  build/loaders/loader-context.js
Labels: bugfix

#553 Release v1.11.4
  package.json
Labels: release

#557 Fix skipped transpilation of async functions in certain instances
  build/get-babel-config.js
  entries/client-public-path.js
  package.json
  test/cli/build.js
  test/compiler/api.js
  test/fixtures/transpile-async-plugin/src/main.js
  test/fixtures/transpile-async-plugin/src/plugin.js
  yarn.lock
Labels: WIP, bugfix

#558 Release v1.11.5
  package.json
Labels: release

#540 Add nodeBuiltins option to fusionrc.js, remove unused and undocumented config
  build/compiler.js
  build/load-fusionrc.js
  docs/fusionrc.md
  test/cli/dev.js
  test/fixtures/fusionrc/.fusionrc.js
  test/fixtures/fusionrc/src/main.js
Labels: refactor

#559 Add gql macro from fusion-apollo
  .gitignore
  build/babel-plugins/babel-plugin-gql/index.js
  build/babel-plugins/babel-plugin-gql/test/fixtures/expected-import-destructuring
  build/babel-plugins/babel-plugin-gql/test/fixtures/expected-import-destructuring-as
  build/babel-plugins/babel-plugin-gql/test/fixtures/input-import-destructuring
  build/babel-plugins/babel-plugin-gql/test/fixtures/input-import-destructuring-as
  build/babel-plugins/babel-plugin-gql/test/fixtures/input-wrong-arg
  build/babel-plugins/babel-plugin-gql/test/index.js
  build/compiler.js
  build/get-babel-config.js
  build/loaders/gql-loader.js
  build/loaders/index.js
  test/cli/build.js
  test/cli/dev.js
  test/fixtures/gql/.fusionrc.js
  test/fixtures/gql/node_modules/fusion-apollo/index.js
  test/fixtures/gql/src/main.js
  test/fixtures/gql/src/schema.gql
  test/index.js
Labels: feature

#561 Fix test gitignores
  .gitignore
  test/fixtures/gql/.gitignore
  test/fixtures/transpile-node-modules/.gitignore
Labels: bugfix

#563 Release v1.12.0-0
  package.json
Labels: release

#566 Fix SSR plugin render CSP nonce
  plugins/ssr-plugin.js
Labels: bugfix

#565 Fix `fusion dev --dir`
  build/dev-runtime.js
  test/cli/dev.js
  test/run-command.js
Labels: bugfix

#570 Fix issue with babel blacklist regexes
  build/compiler.js
  test/compiler/api.js
  test/fixtures/custom-babel/.fusionrc.js
  test/fixtures/custom-babel/.gitignore
  test/fixtures/custom-babel/node_modules/mapbox-gl/index.js
  test/fixtures/custom-babel/node_modules/other/index.js
  test/fixtures/custom-babel/plugin.js
  test/fixtures/custom-babel/src/main.js
Labels: bugfix

#571 Release v1.12.1-0
  package.json
Labels: release

#572 Add specialized build for modern browsers
  README.md
  build/compiler.js
  build/get-babel-config.js
  build/get-webpack-config.js
  build/jest/jest-transformer.js
  build/load-fusionrc.js
  build/loaders/chunk-manifest-loader.js
  build/merge-chunk-metadata.js
  build/plugins/child-compilation-plugin.js
  build/plugins/chunk-id-prefix-plugin.js
  build/plugins/client-chunk-metadata-state-hydrator-plugin.js
  build/plugins/i18n-discovery-plugin.js
  build/shared-state-containers.js
  build/types.js
  commands/build.js
  commands/dev.js
  commands/index.js
  commands/profile.js
  entries/client-entry.js
  entries/client-public-path.js
  entries/server-entry.js
  package.json
  plugins/critical-chunk-ids-plugin.js
  plugins/ssr-plugin.js
  test/cli/build.js
  test/compiler/api.js
  test/compiler/errors.js
  test/fixtures/server-startup-control/delayed-compilation.js
  yarn.lock
Labels: feature

#575 Release v1.12.1
  package.json
Labels: release

#574 Release v1.13.0-beta.0
  package.json
Labels: release

#576 Ensure nonces are set for all scripts (including dynamically loaded scripts)
  entries/client-public-path.js
  plugins/ssr-plugin.js
  test/cli/build.js
Labels: bugfix

#577 Release v1.13.0-beta.1
  package.json
Labels: release

#579 Set script nonce attribute rather than property
  plugins/ssr-plugin.js
  test/cli/build.js
Labels: bugfix

#581 Release v1.13.0-beta.2
  package.json
Labels: release

#582 Load modern bundles as regular scripts
  plugins/ssr-plugin.js
  test/cli/build.js
Labels: bugfix

#583 Release v1.13.0-beta.3
  package.json
Labels: release

#573 Update gql loader to use gql tag
  build/loaders/gql-loader.js
  test/fixtures/gql/.gitignore
  test/fixtures/gql/node_modules/graphql-tag/index.js
Labels: feature

#584 Release v1.13.0-beta.4
  package.json
Labels: ci, release

#587 Release v1.13.0-beta.5
  package.json
Labels: release

#588 Fix issue with coverage and gql macro
  .gitignore
  build/babel-plugins/babel-plugin-gql/index.js
  build/babel-plugins/babel-plugin-gql/test/fixtures/expected-inline-import-destructuring
  build/babel-plugins/babel-plugin-gql/test/index.js
  test/cli/test.js
Labels: bugfix

#589 Release v1.13.0-beta.6
  package.json
Labels: release

#591 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#593 Force class transpilation in modern bundle to workaround bugs in Edge
  build/get-babel-config.js
Labels: bugfix

#597 Fix server-side only assets in development
  build/compiler.js
  build/get-webpack-config.js
  build/loaders/file-loader.js
  lib/simple-webpack-dev-middleware/index.js
  lib/simple-webpack-dev-middleware/lib/GetFilenameFromUrl.js
  lib/simple-webpack-dev-middleware/lib/PathJoin.js
  lib/simple-webpack-dev-middleware/lib/Shared.js
  plugins/assets-plugin.js
  test/fixtures/assets/src/main.js
  test/fixtures/assets/src/server-asset.js
Labels: bugfix

#600 Fix SVG optimization so it doesn't remove symbols for external `<use>` tags
  lib/compression/svgo-webpack-plugin.js
  test/cli/build.js
  test/fixtures/compress-assets/src/assets/SVG_logo.svg
Labels: bugfix

#596 Add testMatch/testRegex options to `fusion test`
  build/jest/base-jest-config.js
  build/test-runtime.js
  commands/index.js
  commands/test.js
  test/cli/test.js
  test/fixtures/test-jest-app/src/__foo__/passes.js
Labels: feature
