Repository fusionjs/fusion-cli, pull requests merged in 2019-04, with the labels that each got.

#753 Release v1.18.2-alpha.2
  package.json
Labels: release

#755 Release v1.18.2
  package.json
Labels: release

#752 Fix EventEmitter leak in dev-runtime
  build/dev-runtime.js
  test/e2e/server-startup-control/test.js
Labels: bugfix

#757 Revert change to server-startup-control timeout
  test/e2e/server-startup-control/test.js
Labels: bugfix

#760 Release v1.18.3
  package.json
Labels: release

#762 Update base jest config to ignore __generated__ directory when collecting coverage
  build/jest/base-jest-config.js
Labels: bugfix

#761 Add flags to optionally disable zopfli compression and minification
  build/compiler.js
  build/get-webpack-config.js
  commands/build.js
Labels: feature
