Repository fusionjs/fusion-cli, pull requests merged in 2019-01, with the labels that each got.

#610 Add bundling of service worker entry
  build/babel-plugins/babel-plugin-sw/README.md
  build/babel-plugins/babel-plugin-sw/index.js
  build/babel-plugins/babel-plugin-sw/test/fixtures/expected-import-destructuring
  build/babel-plugins/babel-plugin-sw/test/fixtures/expected-import-destructuring-as
  build/babel-plugins/babel-plugin-sw/test/fixtures/input-import-destructuring
  build/babel-plugins/babel-plugin-sw/test/fixtures/input-import-destructuring-as
  build/babel-plugins/babel-plugin-sw/test/index.test.js
  build/babel-plugins/babel-plugin-utils/visit-named-module.js
  build/compiler.js
  build/get-babel-config.js
  build/get-webpack-config.js
  build/loaders/index.js
  build/loaders/sw-loader.js
  build/plugins/child-compilation-plugin.js
  docs/service-workers.md
  package.json
  sw.js
  test/e2e/noop-sw/fixture/src/main.js
  test/e2e/noop-sw/fixture/src/sw.js
  test/e2e/noop-sw/test.js
  yarn.lock
Labels: feature

#661 Release v1.14.0
  package.json
Labels: release

#658 Add preserveNames flag
  README.md
  build/compiler.js
  build/get-webpack-config.js
  commands/build.js
  commands/index.js
  test/e2e/preserve-names/fixture/src/main.js
  test/e2e/preserve-names/test.js
Labels: feature

#664 Serve modern bundles to Chromium
  plugins/ssr-plugin.js
Labels: bugfix

#666 Remove duplicated worker index
  .buildkite/pipeline.yml
Labels: refactor

#671 Release v1.15.0
  package.json
Labels: release

#672 Fix browser field resolution in dependencies of sw bundle when es2015/es2017 fields are present
  build/get-webpack-config.js
  test/e2e/noop-sw/fixture/src/other/dist/browser.es2015.es.js
  test/e2e/noop-sw/fixture/src/other/dist/browser.es2017.es.js
  test/e2e/noop-sw/fixture/src/other/dist/browser.es5.es.js
  test/e2e/noop-sw/fixture/src/other/dist/browser.es5.js
  test/e2e/noop-sw/fixture/src/other/dist/index.es.js
  test/e2e/noop-sw/fixture/src/other/dist/index.js
  test/e2e/noop-sw/fixture/src/other/package.json
  test/e2e/noop-sw/fixture/src/sw.js
  test/e2e/noop-sw/test.js
Labels: bugfix

#674 Release v1.15.1-0
  package.json
Labels: release

#675 Fix typo in comment
  build/compiler.js
Labels: refactor

#673 Dump stats object when build command errors
  commands/build.js
Labels: bugfix

#677 Move fusion-plugin-universal-events into devDependencies
  package.json
  yarn.lock
Labels: bugfix

#678 Release v1.15.1
  package.json
Labels: release

#682 Release v1.15.2-0
  package.json
Labels: release

#683 Upgrade jest/babel-jest
  package.json
  yarn.lock
Labels: feature

#685 Fix testing with hoisted node_modules
  README.md
  build/test-runtime.js
  commands/index.js
Labels: bugfix

#688 Use graphql-tag loader for fragment import support
  build/babel-plugins/babel-plugin-gql/index.js
  build/jest/base-jest-config.js
  build/jest/graphql-jest-transformer.js
  build/loaders/gql-loader.js
  build/loaders/index.js
  package.json
  test/e2e/gql/fixture/src/__tests__/schema.js
  test/e2e/gql/fixture/src/fragment.gql
  test/e2e/gql/fixture/src/main.js
  test/e2e/gql/fixture/src/query.gql
  yarn.lock
Labels: feature
