Repository fusionjs/fusion-cli, pull requests merged in 2019-02, with the labels that each got.

#693 Release v1.16.0-2
  package.json
Labels: release

#694 Release v1.16.0
  package.json
Labels: release

#698 Improve test reliability
  test/e2e/test-jest-app/test.js
Labels: performance, refactor

#699 Improve tests
  .flowconfig
  package.json
  test/e2e/gql/__snapshots__/test.js.snap
  test/e2e/gql/fixture/src/__tests__/schema.js
  test/e2e/gql/test.js
  test/e2e/i18n/fixture/.fusionrc.js
  test/e2e/i18n/fixture/.gitignore
  test/e2e/i18n/fixture/src/main.js
  test/e2e/i18n/fixture/src/root.js
  test/e2e/i18n/test.js
  yarn.lock
Labels: refactor

#700 Add deps that are required by tests
  package.json
  yarn.lock
Labels: refactor

#702 Add babel-plugin-transform-styletron-display-name
  build/get-babel-config.js
  package.json
  yarn.lock
Labels: bugfix

#706 Add 'runInBand' to Jest option whitelist
  build/jest/cli-options.js
Labels: feature

#707 Release v1.16.1-0
  package.json
Labels: release

#709 Apply graphql-tag/loader on graphql/gql files
  build/babel-plugins/babel-plugin-gql/index.js
  build/babel-plugins/babel-plugin-gql/test/fixtures/expected-import-destructuring
  build/babel-plugins/babel-plugin-gql/test/fixtures/expected-import-destructuring-as
  build/get-babel-config.js
  build/get-webpack-config.js
  build/loaders/index.js
  test/e2e/gql/__snapshots__/test.js.snap
  test/e2e/gql/fixture/node_modules/graphql-tag/index.js
  test/e2e/gql/fixture/src/__tests__/schema.js
  test/e2e/gql/fixture/src/main.js
  test/e2e/gql/fixture/src/query.gql
  test/e2e/gql/fixture/src/schema.graphql
  test/e2e/gql/test.js
Labels: bugfix

#710 Release v1.16.2-0
  package.json
Labels: release

#711 Keep file system watching enabled if --no-hmr
  commands/dev.js
Labels: bugfix

#714 Release v1.17.0-1
  package.json
Labels: release

#715 Release v1.17.0
  package.json
Labels: release

#716 Ensure that we don't report coverage for files in __tests__
  build/jest/base-jest-config.js
  test/e2e/test-jest-app/test.js
Labels: bugfix

#697 Add module id dynamic import instrumentation
  build/plugins/instrumented-import-dependency-template-plugin.js
Labels: feature

#717 Release v1.18.0-alpha.0
  package.json
Labels: release

#718 Fix Windows bugs
  build/get-webpack-config.js
Labels: bugfix
