Repository fusionjs/fusion-cli, pull requests merged in 2019-03, with the labels that each got.

#720 Implement worker loader
  build/babel-plugins/babel-plugin-workerurl/index.js
  build/babel-plugins/babel-plugin-workerurl/test/fixtures/expected-import-destructuring
  build/babel-plugins/babel-plugin-workerurl/test/fixtures/expected-import-destructuring-as
  build/babel-plugins/babel-plugin-workerurl/test/fixtures/input-import-destructuring
  build/babel-plugins/babel-plugin-workerurl/test/fixtures/input-import-destructuring-as
  build/babel-plugins/babel-plugin-workerurl/test/fixtures/input-wrong-arg
  build/babel-plugins/babel-plugin-workerurl/test/index.test.js
  build/get-babel-config.js
  build/get-webpack-config.js
  build/loaders/index.js
  build/loaders/worker-loader.js
  package.json
  test/e2e/worker/fixture/src/main.js
  test/e2e/worker/fixture/src/root.js
  test/e2e/worker/fixture/src/worker.js
  test/e2e/worker/fixture/src/worker2.js
  test/e2e/worker/fixture/src/worker2Import.js
  test/e2e/worker/test.js
  yarn.lock
Labels: feature

#724 Release v1.18.0-alpha.3
  package.json
Labels: release

#725 Fix preloading when chunk group contains multiple chunks
  build/plugins/client-chunk-metadata-state-hydrator-plugin.js
  test/e2e/dynamic-import-app-group-preloading/fixture/src/main.js
  test/e2e/dynamic-import-app-group-preloading/fixture/src/root.js
  test/e2e/dynamic-import-app-group-preloading/fixture/src/split-a.js
  test/e2e/dynamic-import-app-group-preloading/fixture/src/split-b.js
  test/e2e/dynamic-import-app-group-preloading/fixture/src/split-shared-ab.js
  test/e2e/dynamic-import-app-group-preloading/test.js
Labels: bugfix

#727 Release v1.18.0
  package.json
Labels: release

#728 Fix jest test chunking
  .buildkite/nodeTests
  get-test-files.js
Labels: refactor

#723 Add link to progressively enhanced bundles docs in legacy browser message
  plugins/ssr-plugin.js
Labels: bugfix

#730 Fix broken e2e test
  test/e2e/dynamic-import-app-group-preloading/fixture/src/root.js
Labels: bugfix

#729 Fix --no-hmr flag
  build/compiler.js
  build/get-webpack-config.js
  commands/dev.js
Labels: bugfix

#733 Release v1.18.0-debugging
  package.json
Labels: release

#734 Release v1.18.1-0
  package.json
Labels: release

#735 Release v1.18.0-debugging-1
  package.json
Labels: release

#736 Release v1.18.2-alpha.0
  package.json
Labels: release

#738 Release v1.18.1
  package.json
Labels: release

#743 Support gql macro from fusion-plugin-apollo
  build/babel-plugins/babel-plugin-gql/index.js
  build/babel-plugins/babel-plugin-gql/test/fixtures/expected-import-destructuring
  build/babel-plugins/babel-plugin-gql/test/fixtures/input-import-destructuring
Labels: bugfix

#744 Release v1.18.2-0
  package.json
Labels: release

#745 Use webpack native json behavior for loading json files via assetUrl
  build/loaders/json-loader.js
  test/e2e/assets/fixture/src/main.js
  test/e2e/assets/fixture/src/static/test.json
  test/e2e/assets/test.js
Labels: bugfix

#746 Make tests less reliant on how exactly babel transpiles template strings
  test/e2e/empty/test.js
  test/e2e/gql/test.js
  test/e2e/noop-test/fixture/src/main.js
  test/e2e/noop-test/test.js
  test/e2e/noop/test.js
  test/e2e/test-jest-app/test.js
  test/e2e/test-jest-babel/test.js
Labels: refactor

#742 Move assets plugin registration to after app-level plugins
  entries/server-entry.js
  test/e2e/multiple-asset-servers/fixture/.fusionrc.js
  test/e2e/multiple-asset-servers/fixture/src/main.js
  test/e2e/multiple-asset-servers/fixture/src/server-asset.js
  test/e2e/multiple-asset-servers/fixture/src/static/test-server-asset.txt
  test/e2e/multiple-asset-servers/fixture/src/static/test.css
  test/e2e/multiple-asset-servers/fixture/src/static/test.json
  test/e2e/multiple-asset-servers/test.js
Labels: bugfix

#747 Release v1.18.2-1
  package.json
Labels: release

#750 Fix issue with errors being swallowed in child compilations
  build/compiler.js
  test/e2e/colocated-tests-error/__snapshots__/test.js.snap
  test/e2e/errors.js
  test/e2e/missing-module/__snapshots__/test.js.snap
  test/e2e/syntax-error/__snapshots__/test.js.snap
Labels: bugfix

#751 Release v1.18.3-0
  package.json
Labels: release
